# ------------------------------------------------------------------------------
# Build.yml
# ------------------------------------------------------------------------------

name: Build

on:
  push:
  pull_request:
    branches-ignore:
      - master
      - main
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: windows-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: dotnet tool install --global NETFrameworkTool
      - run: NETFrameworkTool --net 4.0 --install
      - run: NETFrameworkTool --net 4.5 --install
      
      - name: Run './build/build.cmd'
        run: ./build/build.cmd --root ./build
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          SignFile: ${{ secrets.SIGN_FILE }}
          SignPassword: ${{ secrets.SIGN_PASSWORD }}
          NugetApiUrl: ${{ secrets.NUGET_API_URL }}
          NugetApiKey: ${{ secrets.NUGET_API_KEY }}
